### ISSUE TITLE
Sea Brick crafting balance

### ISSUE THREAD

**Issue by elr011081** [Michiel1973/amazonia#408]
in the Sea Stone Brick mod the crafting currently outputs 1 brick per 4 stone which is a loss of 3 stone resources for every brick.  Simple fix, add 4 to each sea stone brick output for the variety of colors, example: (line 125) register_blockbrick_craft("seastonebrick:seastonebrick", {{'seastone:seastone', 'seastone:seastone'}, {'seastone:seastone', 'seastone:seastone'}}) 

change to > register_blockbrick_craft("seastonebrick:seastonebrick 4", {{'seastone:seastone', 'seastone:seastone'}, {'seastone:seastone', 'seastone:seastone'}}) 

all outputs found @ lines 125-131 in init.lua

thank you

**Comment by Michiel1973** [comment]
don't see an issue with that, in line with other bricks. Done, will be live after restart tomorrow 6am GMT+2
