### ISSUE TITLE
Nets

### ISSUE THREAD

**Issue by BigBitsaByte** [Michiel1973/amazonia#79]
Using the red net (for animals) when you right click on them w/ the net you get a "You are not the owner of said animal"
![net](https://user-images.githubusercontent.com/63552914/79395766-5c3b8980-7f48-11ea-89d1-5facee1ffc58.png)

**Comment by Michiel1973** [comment]
yup, same issue, parrots come from Petz mod, nets come from mobs mod.

Reviewing whether to remove the nets from mobs mod altogether.

**Comment by Michiel1973** [comment]
Looked into it further, this is not actually a bug, just poor messaging from the game.

You can only catch the parrot in the net if you own it, to own it you need to tame it first. I'll look into updating the message displayed.

**Comment by Michiel1973** [comment]
resolved - added ", or it has not been tamed yet" to make clear that you're either not the owner or you haven't tamed this pet.
