### ISSUE TITLE
gliders last forever

### ISSUE THREAD

**Issue by Michiel1973** [Michiel1973/amazonia#97]
gliders are cheap to make and never wear out, making the repair option useless.

**Comment by BigBitsaByte** [comment]
What type of gliders... Mine has a status bar that gets depleted. Then breaks when it runs out. Had one break on me the other day. Had to make a new one.

**Comment by Michiel1973** [comment]
fixed by https://github.com/Michiel1973/amazonia/pull/107  

:)
